name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Test
        run: npm test -- --passWithNoTests

      - name: Verify build output
        run: |
          test -f dist/index.js
          test -f dist/server.js
          test -d dist/types

      - name: Check server help
        run: node dist/index.js --help

      - name: Test STDIO mode startup
        run: |
          timeout 3s node dist/index.js --transport stdio < /dev/null || [ $? -eq 124 ]

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: dist/
